# Generated by Django 2.2 on 2021-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publishermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('author', models.ManyToManyField(to='employee.AuthorModel')),
            ],
        ),
    ]
