# Generated by Django 2.2 on 2021-11-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
