# Generated by Django 2.2 on 2021-11-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_1', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
